//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinsinavAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBolumEgitmen
    {
        public int bolumEgitmenid { get; set; }
        public Nullable<int> bolumid { get; set; }
        public Nullable<int> egitmenid { get; set; }
    
        public virtual tblBolum tblBolum { get; set; }
        public virtual tblEgitmen tblEgitmen { get; set; }
    }
}
