//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinsinavAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEgitmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEgitmen()
        {
            this.tblBolumEgitmen = new HashSet<tblBolumEgitmen>();
            this.tblEgitmenDers = new HashSet<tblEgitmenDers>();
            this.tblKullanici = new HashSet<tblKullanici>();
            this.tblSinav = new HashSet<tblSinav>();
        }
    
        public int egitmenid { get; set; }
        public string egitmenad { get; set; }
        public string egitmensoyad { get; set; }
        public string egitmeneposta { get; set; }
        public Nullable<int> bolumid { get; set; }
        public Nullable<int> yetkiturid { get; set; }
        public Nullable<int> fakulteid { get; set; }
        public Nullable<int> dersid { get; set; }
    
        public virtual tblBolum tblBolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBolumEgitmen> tblBolumEgitmen { get; set; }
        public virtual tblDers tblDers { get; set; }
        public virtual tblEgitmen tblEgitmen1 { get; set; }
        public virtual tblEgitmen tblEgitmen2 { get; set; }
        public virtual tblFakulte tblFakulte { get; set; }
        public virtual tblYetkiTur tblYetkiTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEgitmenDers> tblEgitmenDers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKullanici> tblKullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSinav> tblSinav { get; set; }
    }
}
