//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinsinavAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKullanici()
        {
            this.tblYetki = new HashSet<tblYetki>();
        }
    
        public int kullaniciid { get; set; }
        public string kullaniciad { get; set; }
        public string kullanicisifre { get; set; }
        public Nullable<int> yetkiturid { get; set; }
        public string Role { get; set; }
        public Nullable<int> egitmenid { get; set; }
        public Nullable<int> ogrenciid { get; set; }
        public Nullable<int> ogrenciisleriid { get; set; }
    
        public virtual tblEgitmen tblEgitmen { get; set; }
        public virtual tblOgrenci tblOgrenci { get; set; }
        public virtual tblOgrenciIsleri tblOgrenciIsleri { get; set; }
        public virtual tblYetkiTur tblYetkiTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblYetki> tblYetki { get; set; }
    }
}
