//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinsinavAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenciIsleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOgrenciIsleri()
        {
            this.tblKullanici = new HashSet<tblKullanici>();
        }
    
        public int ogrenciisleriid { get; set; }
        public string ogrenciisleriad { get; set; }
        public string ogrenciislerisifre { get; set; }
        public Nullable<int> yetkiturid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKullanici> tblKullanici { get; set; }
        public virtual tblYetkiTur tblYetkiTur { get; set; }
    }
}
