//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinsinavAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOgrenci()
        {
            this.tblKullanici = new HashSet<tblKullanici>();
            this.tblOgrenciDers = new HashSet<tblOgrenciDers>();
            this.tblOgrenciCevap = new HashSet<tblOgrenciCevap>();
            this.tblOgrenciPuan = new HashSet<tblOgrenciPuan>();
        }
    
        public int ogrenciid { get; set; }
        public string ogrenciad { get; set; }
        public string ogrencisoyad { get; set; }
        public Nullable<int> ogrencino { get; set; }
        public string ogrencieposta { get; set; }
        public Nullable<int> bolumid { get; set; }
        public Nullable<int> yetkiturid { get; set; }
        public Nullable<int> fakulteid { get; set; }
        public Nullable<int> dersid { get; set; }
    
        public virtual tblBolum tblBolum { get; set; }
        public virtual tblDers tblDers { get; set; }
        public virtual tblFakulte tblFakulte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKullanici> tblKullanici { get; set; }
        public virtual tblYetkiTur tblYetkiTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciDers> tblOgrenciDers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciCevap> tblOgrenciCevap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciPuan> tblOgrenciPuan { get; set; }
    }
}
