//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinsinavAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSinav
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSinav()
        {
            this.tblSinavSoru = new HashSet<tblSinavSoru>();
            this.tblSoru = new HashSet<tblSoru>();
            this.tblOgrenciCevap = new HashSet<tblOgrenciCevap>();
            this.tblOgrenciPuan = new HashSet<tblOgrenciPuan>();
        }
    
        public int sinavid { get; set; }
        public string sinavad { get; set; }
        public Nullable<System.DateTime> sinavtarih { get; set; }
        public Nullable<int> dersid { get; set; }
        public Nullable<int> egitmenid { get; set; }
        public Nullable<System.DateTime> sinavbitis { get; set; }
    
        public virtual tblDers tblDers { get; set; }
        public virtual tblEgitmen tblEgitmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSinavSoru> tblSinavSoru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSoru> tblSoru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciCevap> tblOgrenciCevap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciPuan> tblOgrenciPuan { get; set; }
    }
}
