//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinsinavAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYetki
    {
        public int yetkiid { get; set; }
        public Nullable<int> kullaniciid { get; set; }
        public Nullable<int> yetkiturid { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
        public virtual tblYetkiTur tblYetkiTur { get; set; }
    }
}
